// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=5b35c46cb5
ROOST_METHOD_SIG_HASH=01eaa9028e


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Testing sendVideo method in Telegram module', () => {
  let telegram;
  let chatId;
  let video;
  let options;
  let fileOptions;

  beforeAll(() => {
    telegram = new Telegram();
    chatId = '123456';
    video = 'video.mp4';
    options = {};
    fileOptions = {};
  });

  test('should successfully send a video', async () => {
    const sendSpy = jest.spyOn(telegram, '_request');
    await telegram.sendVideo(chatId, video, options, fileOptions);
    expect(sendSpy).toHaveBeenCalledWith('sendVideo', expect.any(Object));
  });

  test('should fail to send a video due to missing video file', async () => {
    video = 'non_existent_video.mp4';
    await expect(telegram.sendVideo(chatId, video, options, fileOptions)).rejects.toThrow();
  });

  test('should fail to send a video due to missing chatId', async () => {
    chatId = '';
    await expect(telegram.sendVideo(chatId, video, options, fileOptions)).rejects.toThrow();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });
});
