// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=3854312670
ROOST_METHOD_SIG_HASH=18c9806c2e


*/

// ********RoostGPT********
const Bot = require('./express');
const bot = new Bot();

describe('Bot', () => {
  let msg;

  beforeEach(() => {
    msg = {
      chat: {
        id: 1
      }
    };
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should send a message', () => {
    bot.sendMessage = jest.fn();
    bot.on('message', msg);
    expect(bot.sendMessage).toHaveBeenCalledWith(msg.chat.id, 'I am alive!');
  });

  test('should not send a message if no message is received', () => {
    bot.sendMessage = jest.fn();
    bot.on('message', null);
    expect(bot.sendMessage).not.toHaveBeenCalled();
  });
});
