// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=8db0034734
ROOST_METHOD_SIG_HASH=1bf246a4a0


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  describe('sendContact', () => {
    test('should call _request with correct parameters', () => {
      const chatId = 1234;
      const phoneNumber = '1234567890';
      const firstName = 'John';

      telegram.sendContact(chatId, phoneNumber, firstName);

      expect(telegram._request).toHaveBeenCalledWith('sendContact', {
        form: {
          chat_id: chatId,
          phone_number: phoneNumber,
          first_name: firstName
        }
      });
    });

    test('should call _request with correct parameters and form', () => {
      const chatId = 1234;
      const phoneNumber = '1234567890';
      const firstName = 'John';
      const form = {
        last_name: 'Doe',
        vcard: 'vCard'
      };

      telegram.sendContact(chatId, phoneNumber, firstName, form);

      expect(telegram._request).toHaveBeenCalledWith('sendContact', {
        form: {
          chat_id: chatId,
          phone_number: phoneNumber,
          first_name: firstName,
          ...form
        }
      });
    });
  });
});
