// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=84ece2fe57
ROOST_METHOD_SIG_HASH=1c68dc0b7c


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('hasOpenWebHook', () => {
    
    test('should return true if webHook is open', () => {
      telegram._webHook = { isOpen: jest.fn().mockReturnValue(true) };
      expect(telegram.hasOpenWebHook()).toBe(true);
    });

    test('should return false if webHook is not open', () => {
      telegram._webHook = { isOpen: jest.fn().mockReturnValue(false) };
      expect(telegram.hasOpenWebHook()).toBe(false);
    });

    test('should return false if webHook is undefined', () => {
      telegram._webHook = null;
      expect(telegram.hasOpenWebHook()).toBe(false);
    });

  });

});
