// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=bc3b78d8aa
ROOST_METHOD_SIG_HASH=2096446721


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram Bot API', () => {
  let telegram;

  beforeAll(() => {
    telegram = new Telegram();
  });

  describe('declineChatJoinRequest method', () => {
    test('should return a request with correct chatId and userId', () => {
      const chatId = '12345';
      const userId = '67890';
      const form = {};

      const expectedResponse = {
        form: {
          chat_id: chatId,
          user_id: userId
        }
      };

      const response = telegram.declineChatJoinRequest(chatId, userId, form);
      expect(response).toEqual(expectedResponse);
    });

    test('should throw an error if chatId or userId is missing', () => {
      const chatId = '12345';
      const userId = '';
      const form = {};

      expect(() => {
        telegram.declineChatJoinRequest(chatId, userId, form)
      }).toThrow();
    });
  });
});
