// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=cfb4d3acf6
ROOST_METHOD_SIG_HASH=23cce9b088


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('unhideGeneralForumTopic', () => {
    test('should send a request with the correct parameters', () => {
      const chatId = '12345';
      const form = { key: 'value' };

      // Spy on the _request method
      const spy = jest.spyOn(telegram, '_request');
      
      // Call the method
      telegram.unhideGeneralForumTopic(chatId, form);
      
      // Check the spy
      expect(spy).toHaveBeenCalledWith('unhideGeneralForumTopic', { form: { chat_id: chatId, key: 'value' } });
    });

    test('should add chatId to the form if not present', () => {
      const chatId = '12345';

      // Spy on the _request method
      const spy = jest.spyOn(telegram, '_request');

      // Call the method
      telegram.unhideGeneralForumTopic(chatId);

      // Check the spy
      expect(spy).toHaveBeenCalledWith('unhideGeneralForumTopic', { form: { chat_id: chatId } });
    });
  });
});
