// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=27901af30e
ROOST_METHOD_SIG_HASH=28c982bc75


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('editMessageLiveLocation', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('should correctly set latitude and longitude in the form and call _request with correct arguments', () => {
    const latitude = 50.0452;
    const longitude = 14.4378;
    const form = {};

    telegram.editMessageLiveLocation(latitude, longitude, form);

    expect(form.latitude).toBe(latitude);
    expect(form.longitude).toBe(longitude);
    expect(telegram._request).toHaveBeenCalledWith('editMessageLiveLocation', { form });
  });

  test('should throw an error if latitude or longitude are not provided', () => {
    const latitude = null;
    const longitude = 14.4378;
    const form = {};

    expect(() => {
      telegram.editMessageLiveLocation(latitude, longitude, form);
    }).toThrow();

    const latitude2 = 50.0452;
    const longitude2 = null;

    expect(() => {
      telegram.editMessageLiveLocation(latitude2, longitude2, form);
    }).toThrow();
  });
});
