// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=1a8d4f8ddf
ROOST_METHOD_SIG_HASH=319b5ab936


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeAll(() => {
    telegram = new Telegram();
  });

  describe('copyMessage', () => {
    test('should correctly assign chatId, fromChatId, and messageId to form', () => {
      const chatId = '1234';
      const fromChatId = '5678';
      const messageId = '91011';
      const form = {};

      telegram.copyMessage(chatId, fromChatId, messageId, form);

      expect(form.chat_id).toEqual(chatId);
      expect(form.from_chat_id).toEqual(fromChatId);
      expect(form.message_id).toEqual(messageId);
    });

    test('should make a request with the correct method and form', () => {
      const chatId = '1234';
      const fromChatId = '5678';
      const messageId = '91011';
      const form = {};

      const _requestSpy = jest.spyOn(telegram, '_request').mockImplementation(() => {});

      telegram.copyMessage(chatId, fromChatId, messageId, form);

      expect(_requestSpy).toHaveBeenCalledWith('copyMessage', { form });
    });
  });
});
