// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=0d4efefee8
ROOST_METHOD_SIG_HASH=324af6627f


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('leaveChat', () => {
    it('should call _request with correct parameters', () => {
      const chatId = 12345;
      const form = { someData: 'test' };

      const spy = jest.spyOn(telegram, '_request');
      telegram.leaveChat(chatId, form);

      expect(spy).toHaveBeenCalledWith('leaveChat', { form: { someData: 'test', chat_id: chatId } });
    });

    it('should throw an error if no chatId is provided', () => {
      expect(() => {
        telegram.leaveChat();
      }).toThrow('chatId is required');
    });
  });
});

afterEach(() => {
  jest.clearAllMocks();
});
