// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=57a3137e16
ROOST_METHOD_SIG_HASH=352e38c3c9


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('removeReplyListener', () => {
    test('should remove a reply listener by id', () => {
      const replyListenerId = '123';
      telegram._replyListeners.push({ id: replyListenerId });

      const removedListener = telegram.removeReplyListener(replyListenerId);

      expect(removedListener.id).toBe(replyListenerId);
      expect(telegram._replyListeners).toHaveLength(0);
    });

    test('should return null if no listener is found by id', () => {
      const replyListenerId = '123';

      const removedListener = telegram.removeReplyListener(replyListenerId);

      expect(removedListener).toBeNull();
      expect(telegram._replyListeners).toHaveLength(0);
    });
  });
});
