// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=fc6e18f2ee
ROOST_METHOD_SIG_HASH=383960596f


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('revokeChatInviteLink', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  it('should call _request method with correct arguments', () => {
    const chatId = '123';
    const inviteLink = 'testLink';
    const form = {};

    telegram.revokeChatInviteLink(chatId, inviteLink, form);

    expect(telegram._request).toHaveBeenCalledWith('revokeChatInviteLink', {
      form: {
        chat_id: chatId,
        invite_link: inviteLink,
        ...form
      }
    });
  });

  it('should throw an error if chatId is not provided', () => {
    expect(() => telegram.revokeChatInviteLink()).toThrow('chatId is required');
  });

  it('should throw an error if inviteLink is not provided', () => {
    const chatId = '123';
    expect(() => telegram.revokeChatInviteLink(chatId)).toThrow('inviteLink is required');
  });
});
