// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ccb2f63847
ROOST_METHOD_SIG_HASH=4138cc152b


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram class', () => {
  describe('errors method', () => {
    test('should return errors object', () => {
      expect(Telegram.errors).toBe(errors);
    });

    test('should throw an error if accessed before initialization', () => {
      Telegram.errors = null;
      expect(() => Telegram.errors).toThrow('errors is not defined');
    });

    afterEach(() => {
      Telegram.errors = errors; // Reset to original state after each test
    });
  });
});
