// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=f6fadabfb7
ROOST_METHOD_SIG_HASH=4ea63eb3e8


*/

// ********RoostGPT********
// Importing the required dependencies
const ErrorClass = require('../src/errors');

describe('ErrorClass Tests', () => {
  let data;

  beforeEach(() => {
    data = "This is a test error message";
  });

  test('Should correctly assign message when data is a string', () => {
    const errorInstance = new ErrorClass(data);
    expect(errorInstance.message).toBe(data);
    expect(errorInstance.name).toBe('EFATAL');
    expect(errorInstance.stack).toBeUndefined();
  });

  test('Should correctly assign error and message when data is an error object', () => {
    const errorObj = new Error(data);
    const errorInstance = new ErrorClass(errorObj);
    expect(errorInstance.message).toBe(data);
    expect(errorInstance.name).toBe('EFATAL');
    expect(errorInstance.stack).toBe(errorObj.stack);
  });
});
