// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=534e30ea3c
ROOST_METHOD_SIG_HASH=51b9b89ec1


*/

// ********RoostGPT********
const Telegram = require('../src/telegram');

describe('sendVenue method', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('should populate form correctly and call _request with "sendVenue" and the form', () => {
    const chatId = 'chatId';
    const latitude = 'latitude';
    const longitude = 'longitude';
    const title = 'title';
    const address = 'address';
    const form = {};

    telegram.sendVenue(chatId, latitude, longitude, title, address, form);

    expect(form).toEqual({
      chat_id: chatId,
      latitude: latitude,
      longitude: longitude,
      title: title,
      address: address,
    });
    expect(telegram._request).toHaveBeenCalledWith('sendVenue', { form });
  });

  test('should use an empty object as form if not provided', () => {
    const chatId = 'chatId';
    const latitude = 'latitude';
    const longitude = 'longitude';
    const title = 'title';
    const address = 'address';

    telegram.sendVenue(chatId, latitude, longitude, title, address);

    expect(telegram._request).toHaveBeenCalledWith('sendVenue', {
      form: {
        chat_id: chatId,
        latitude: latitude,
        longitude: longitude,
        title: title,
        address: address,
      },
    });
  });
});
