// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=d167e87a37
ROOST_METHOD_SIG_HASH=571430d28d


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeAll(() => {
    telegram = new Telegram();
  });

  describe('deleteForumTopic', () => {
    test('should successfully delete a forum topic', async () => {
      const chatId = '1234';
      const messageThreadId = '5678';
      const form = {};

      const response = await telegram.deleteForumTopic(chatId, messageThreadId, form);

      expect(response).toBeDefined();
      expect(response.form).toEqual({
        chat_id: chatId,
        message_thread_id: messageThreadId
      });
    });

    test('should fail when chatId is not provided', async () => {
      const messageThreadId = '5678';
      const form = {};

      await expect(telegram.deleteForumTopic(undefined, messageThreadId, form)).rejects.toThrow();
    });

    test('should fail when messageThreadId is not provided', async () => {
      const chatId = '1234';
      const form = {};

      await expect(telegram.deleteForumTopic(chatId, undefined, form)).rejects.toThrow();
    });
  });
});
