// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=c11303dd69
ROOST_METHOD_SIG_HASH=5e1a1336fb


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeAll(() => {
    telegram = new Telegram();
  });

  test('approveChatJoinRequest should send a request with correct parameters', () => {
    const _request = jest.fn();
    telegram._request = _request;

    const chatId = '123';
    const userId = '456';
    const form = {};

    telegram.approveChatJoinRequest(chatId, userId, form);

    expect(_request).toHaveBeenCalledWith('approveChatJoinRequest', {
      form: {
        chat_id: chatId,
        user_id: userId
      }
    });
  });

  test('approveChatJoinRequest should throw an error if chatId is not provided', () => {
    expect(() => {
      telegram.approveChatJoinRequest(undefined, 'userId', {});
    }).toThrow();
  });

  test('approveChatJoinRequest should throw an error if userId is not provided', () => {
    expect(() => {
      telegram.approveChatJoinRequest('chatId', undefined, {});
    }).toThrow();
  });
});
