// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=2f0442e8b4
ROOST_METHOD_SIG_HASH=63679f9345


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  describe('forwardMessages', () => {
    test('should forward messages correctly', () => {
      const chatId = '123';
      const fromChatId = '456';
      const messageIds = ['1', '2', '3'];
      const form = {};

      telegram.forwardMessages(chatId, fromChatId, messageIds, form);

      expect(telegram._request).toHaveBeenCalledWith('forwardMessages', {
        form: {
          chat_id: chatId,
          from_chat_id: fromChatId,
          message_ids: messageIds
        }
      });
    });

    test('should throw error when chatId is not provided', () => {
      const fromChatId = '456';
      const messageIds = ['1', '2', '3'];
      const form = {};

      expect(() => {
        telegram.forwardMessages(undefined, fromChatId, messageIds, form);
      }).toThrow();
    });

    // Add more tests as per your requirements
  });
});
