// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=97ae624eb7
ROOST_METHOD_SIG_HASH=75432b4a85


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('closeGeneralForumTopic', () => {
    test('should return a request with chatId and form data', () => {
      const chatId = 'testChatId';
      const form = { key: 'value' };

      const expectedForm = {
        chat_id: chatId,
        key: 'value'
      };

      telegram._request = jest.fn();

      telegram.closeGeneralForumTopic(chatId, form);

      expect(telegram._request).toHaveBeenCalledWith('closeGeneralForumTopic', { form: expectedForm });
    });

    test('should add chatId to an empty form if no form is provided', () => {
      const chatId = 'testChatId';

      const expectedForm = {
        chat_id: chatId
      };

      telegram._request = jest.fn();

      telegram.closeGeneralForumTopic(chatId);

      expect(telegram._request).toHaveBeenCalledWith('closeGeneralForumTopic', { form: expectedForm });
    });
  });
});
