// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=0c4cad1338
ROOST_METHOD_SIG_HASH=7635a38758


*/

// ********RoostGPT********
const TelegramBot = require('../src/telegram');
const debug = require('debug');

jest.mock('debug', () => {
  return jest.fn().mockImplementation(() => {
    return jest.fn();
  });
});

describe('TelegramBot processUpdate method', () => {
  let bot;

  beforeEach(() => {
    bot = new TelegramBot();
    bot.emit = jest.fn();
  });

  test('should process message update', () => {
    const message = { text: 'hello' };
    bot.processUpdate({ message });
    expect(bot.emit).toHaveBeenCalledWith('message', message, expect.any(Object));
  });

  test('should process edited message update', () => {
    const editedMessage = { text: 'hello edited' };
    bot.processUpdate({ editedMessage });
    expect(bot.emit).toHaveBeenCalledWith('edited_message', editedMessage);
  });

  // Add more test cases for other update types
});
