// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=179879cad5
ROOST_METHOD_SIG_HASH=7a5fd6dbde


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram sendMessage method', () => {
  let telegram;
  
  beforeAll(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('sendMessage should call _request with correct parameters', () => {
    const chatId = '123';
    const text = 'Hello World';
    const form = { parse_mode: 'Markdown' };

    telegram.sendMessage(chatId, text, form);

    expect(telegram._request).toHaveBeenCalledWith('sendMessage', {
      form: {
        chat_id: chatId,
        text: text,
        parse_mode: 'Markdown'
      }
    });
  });

  test('sendMessage should add chatId and text to form', () => {
    const chatId = '456';
    const text = 'Test Message';
    
    telegram.sendMessage(chatId, text);

    expect(telegram._request).toHaveBeenCalledWith('sendMessage', {
      form: {
        chat_id: chatId,
        text: text
      }
    });
  });
});
