// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=b9da736080
ROOST_METHOD_SIG_HASH=81b4f6573f


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram deleteChatStickerSet method', () => {
  let telegram;
  
  beforeAll(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });
  
  beforeEach(() => {
    telegram._request.mockClear();
  });

  test('should correctly set the chat_id in the form object', () => {
    const chatId = '1234';
    const form = {};

    telegram.deleteChatStickerSet(chatId, form);

    expect(form.chat_id).toBe(chatId);
  });

  test('should call the _request method with the correct parameters', () => {
    const chatId = '1234';
    const form = {
      chat_id: chatId
    };

    telegram.deleteChatStickerSet(chatId, form);

    expect(telegram._request).toHaveBeenCalledWith('deleteChatStickerSet', { form });
  });

  test('should throw an error if chatId is not provided', () => {
    expect(() => telegram.deleteChatStickerSet()).toThrow();
  });
});
