// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=5e22202d38
ROOST_METHOD_SIG_HASH=8a83cece90


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('getChatMemberCount', () => {
  let telegram;
  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('should correctly assign chatId to form', () => {
    const chatId = '12345';
    const form = {};
    telegram.getChatMemberCount(chatId, form);
    expect(form.chat_id).toBe(chatId);
  });

  test('should call _request with correct parameters', () => {
    const chatId = '12345';
    const form = {};
    telegram.getChatMemberCount(chatId, form);
    expect(telegram._request).toHaveBeenCalledWith('getChatMemberCount', { form });
  });

  test('should return the result of _request', () => {
    const chatId = '12345';
    const form = {};
    const returnValue = {};
    telegram._request.mockReturnValue(returnValue);
    const result = telegram.getChatMemberCount(chatId, form);
    expect(result).toBe(returnValue);
  });
});
