// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=73ab4a6054
ROOST_METHOD_SIG_HASH=8f22e705bb


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('createChatInviteLink', () => {
  let telegram;
  
  beforeAll(() => {
    telegram = new Telegram();
  });
  
  test('should create chat invite link with valid chat id', async () => {
    const chatId = '123456';
    const form = {};
    
    const response = await telegram.createChatInviteLink(chatId, form);
    
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.result).toHaveProperty('invite_link');
  });
  
  test('should throw error with invalid chat id', async () => {
    const chatId = 'invalid_id';
    const form = {};
    
    await expect(telegram.createChatInviteLink(chatId, form)).rejects.toThrow();
  });

  test('should handle form data correctly', async () => {
    const chatId = '123456';
    const form = { expire_date: Date.now() + 3600 };
    
    const response = await telegram.createChatInviteLink(chatId, form);
    
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.result).toHaveProperty('invite_link');
    expect(response.result).toHaveProperty('expire_date');
  });
});
