// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=e9f503cd97
ROOST_METHOD_SIG_HASH=913db644a7


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram setMyDescription method', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('should correctly call the _request method with the right arguments', () => {
    const form = { description: 'Test description' };
    telegram.setMyDescription(form);
    expect(telegram._request).toHaveBeenCalledWith('setMyDescription', { form });
  });

  test('should handle errors thrown by the _request method', () => {
    telegram._request.mockImplementationOnce(() => {
      throw new Error('Request error');
    });

    expect(() => telegram.setMyDescription()).toThrow('Request error');
  });

  test('should return the result of the _request method', async () => {
    telegram._request.mockReturnValueOnce('Request result');
    const result = await telegram.setMyDescription();
    expect(result).toBe('Request result');
  });
});
