// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=29f24074a9
ROOST_METHOD_SIG_HASH=995d2ec981


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('setChatAdministratorCustomTitle', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  test('should set the correct form data and make request', () => {
    const chatId = '1234';
    const userId = '5678';
    const customTitle = 'Test Title';

    telegram.setChatAdministratorCustomTitle(chatId, userId, customTitle);

    expect(telegram._request).toHaveBeenCalledWith('setChatAdministratorCustomTitle', {
      form: {
        chat_id: chatId,
        user_id: userId,
        custom_title: customTitle
      }
    });
  });

  test('should set the correct form data with additional form parameters and make request', () => {
    const chatId = '1234';
    const userId = '5678';
    const customTitle = 'Test Title';
    const additionalFormParams = {
      disable_notification: true
    };

    telegram.setChatAdministratorCustomTitle(chatId, userId, customTitle, additionalFormParams);

    expect(telegram._request).toHaveBeenCalledWith('setChatAdministratorCustomTitle', {
      form: {
        chat_id: chatId,
        user_id: userId,
        custom_title: customTitle,
        ...additionalFormParams
      }
    });
  });
});
