// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=cde8aa9ac7
ROOST_METHOD_SIG_HASH=9abdfacab4


*/

// ********RoostGPT********
const { _fixReplyParameters } = require('../src/telegram');

describe('_fixReplyParameters function', () => {
  let testObject;

  beforeEach(() => {
    testObject = {
      reply_parameters: {
        key1: "value1",
        key2: "value2"
      }
    };
  });

  test('should convert reply_parameters property to string if it is not a string', () => {
    _fixReplyParameters(testObject);
    expect(typeof testObject.reply_parameters).toBe('string');
  });

  test('should not modify reply_parameters property if it is already a string', () => {
    const testString = "test string";
    testObject.reply_parameters = testString;
    _fixReplyParameters(testObject);
    expect(testObject.reply_parameters).toBe(testString);
  });

  test('should not add reply_parameters property if it does not exist', () => {
    delete testObject.reply_parameters;
    _fixReplyParameters(testObject);
    expect(testObject).not.toHaveProperty('reply_parameters');
  });
});
