// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=0922f6f0c6
ROOST_METHOD_SIG_HASH=9b854128ae


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram Module', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  afterEach(() => {
    telegram = null;
  });

  test('isPolling should return false when _polling is null', () => {
    telegram._polling = null;
    expect(telegram.isPolling()).toBe(false);
  });

  test('isPolling should return false when _polling is not null but isPolling method of _polling returns false', () => {
    telegram._polling = {
      isPolling: jest.fn().mockReturnValue(false),
    };
    expect(telegram.isPolling()).toBe(false);
  });

  test('isPolling should return true when _polling is not null and isPolling method of _polling returns true', () => {
    telegram._polling = {
      isPolling: jest.fn().mockReturnValue(true),
    };
    expect(telegram.isPolling()).toBe(true);
  });
});
