// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=736758f184
ROOST_METHOD_SIG_HASH=ae13e74d85


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeAll(() => {
    telegram = new Telegram();
  });

  describe('getFile', () => {
    it('should return a file when a valid fileId is provided', async () => {
      const fileId = 'validFileId';
      const form = {};

      const file = await telegram.getFile(fileId, form);

      expect(file).toBeDefined();
      expect(file.form.file_id).toBe(fileId);
    });

    it('should throw an error when an invalid fileId is provided', async () => {
      const fileId = 'invalidFileId';
      const form = {};

      await expect(telegram.getFile(fileId, form)).rejects.toThrow();
    });

    it('should attach form data to the request', async () => {
      const fileId = 'validFileId';
      const form = { extraData: 'extraData' };

      const file = await telegram.getFile(fileId, form);

      expect(file.form.extraData).toBe(form.extraData);
    });
  });
});
