// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=194da1a65b
ROOST_METHOD_SIG_HASH=afbfdadd9e


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('editMessageText', () => {
  let telegram;
  let text;
  let form;

  beforeEach(() => {
    telegram = new Telegram();
    text = 'Hello, World!';
    form = {};
  });

  test('should edit message text', async () => {
    const result = await telegram.editMessageText(text, form);
    expect(result).toBeDefined();
    expect(result.form.text).toBe(text);
  });

  test('should throw an error if no text is provided', async () => {
    await expect(telegram.editMessageText('', form)).rejects.toThrow('Text is required');
    await expect(telegram.editMessageText(null, form)).rejects.toThrow('Text is required');
  });

  test('should throw an error if form is not an object', async () => {
    await expect(telegram.editMessageText(text, null)).rejects.toThrow('Form must be an object');
    await expect(telegram.editMessageText(text, 'not an object')).rejects.toThrow('Form must be an object');
  });
});
