// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=b81a9e2bdd
ROOST_METHOD_SIG_HASH=b656e8c8fc


*/

// ********RoostGPT********
// __tests__/express.test.js

const request = require('supertest');
const express = require('express');

const app = express();
const port = process.env.PORT || 3000;

app.listen(port, () => {
  console.log(`Express server is listening on ${port}`);
});

describe('Express server', () => {
  beforeAll(() => {
    console.log('Starting the tests...');
  });

  test('should start the server on the defined port', async () => {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
  });

  test('should return 404 for non-existing routes', async () => {
    const response = await request(app).get('/non-existing-route');
    expect(response.statusCode).toBe(404);
  });

  afterAll(() => {
    app.close();
    console.log('Tests finished.');
  });
});
