// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=67308c27df
ROOST_METHOD_SIG_HASH=be43975d6b


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('hideGeneralForumTopic', () => {
    test('should return a request with chat id and form data', () => {
      const chatId = '123';
      const form = { key: 'value' };
      const expectedRequest = {
        form: {
          chat_id: '123',
          key: 'value'
        }
      };

      telegram._request = jest.fn();

      telegram.hideGeneralForumTopic(chatId, form);
      expect(telegram._request).toHaveBeenCalledWith('hideGeneralForumTopic', expectedRequest);
    });

    test('should throw an error if chat id is not provided', () => {
      expect(() => {
        telegram.hideGeneralForumTopic();
      }).toThrow();
    });
  });
});
