// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=6d190c945d
ROOST_METHOD_SIG_HASH=c4a0a0ca0b


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  afterEach(() => {
    telegram = null;
  });

  test('should clear text listeners', () => {
    telegram._textRegexpCallbacks = ['listener1', 'listener2', 'listener3'];
    telegram.clearTextListeners();
    expect(telegram._textRegexpCallbacks).toEqual([]);
  });

  test('should not throw error when text listeners are already empty', () => {
    telegram._textRegexpCallbacks = [];
    expect(() => telegram.clearTextListeners()).not.toThrow();
  });

});
