// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=fa48091aa8
ROOST_METHOD_SIG_HASH=d242b82d51


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
  });

  describe('getChat', () => {
    it('should call _request method with correct parameters', () => {
      const mockRequest = jest.spyOn(telegram, '_request');
      const chatId = '1234';
      const form = { chat_id: chatId };

      telegram.getChat(chatId);
      expect(mockRequest).toHaveBeenCalledWith('getChat', { form });
    });

    it('should throw error if chatId is not provided', () => {
      expect(() => telegram.getChat()).toThrow();
    });
  });
});
