// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=4db5126727
ROOST_METHOD_SIG_HASH=d535d9c77b


*/

// ********RoostGPT********
const Error = require('./errors');

describe('Error toJSON method', () => {
  let error;

  beforeEach(() => {
    error = new Error();
    error.code = 404;
    error.message = 'Not Found';
  });

  test('should return an object', () => {
    expect(typeof error.toJSON()).toBe('object');
  });

  test('should return correct error code', () => {
    const result = error.toJSON();
    expect(result).toHaveProperty('code', 404);
  });

  test('should return correct error message', () => {
    const result = error.toJSON();
    expect(result).toHaveProperty('message', 'Not Found');
  });

  test('should not return properties other than code and message', () => {
    const result = error.toJSON();
    expect(Object.keys(result)).toEqual(['code', 'message']);
  });
});
