// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=44904fff2f
ROOST_METHOD_SIG_HASH=d840708280


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('getChatAdministrators', () => {
  let telegram;
  let chatId;
  let form;

  beforeEach(() => {
    telegram = new Telegram();
    chatId = '123456';
    form = {};
  });

  test('should set chat_id in form', () => {
    telegram.getChatAdministrators(chatId, form);
    expect(form.chat_id).toBe(chatId);
  });

  test('should send a request with correct method and form', () => {
    const requestSpy = jest.spyOn(telegram, '_request');
    telegram.getChatAdministrators(chatId, form);
    expect(requestSpy).toHaveBeenCalledWith('getChatAdministrators', { form });
  });

  test('should throw an error if chatId is not provided', () => {
    expect(() => telegram.getChatAdministrators()).toThrow();
  });
});
