// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=f30cff2266
ROOST_METHOD_SIG_HASH=e00a134177


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('unpinChatMessage', () => {
  let telegram;
  let chatId;
  let form;

  beforeEach(() => {
    telegram = new Telegram();
    chatId = '123456';
    form = {};
  });

  test('should unpin a chat message successfully', () => {
    const response = telegram.unpinChatMessage(chatId, form);
    expect(response).toBeDefined();
    expect(response).toBeInstanceOf(Promise);
  });

  test('should throw an error when chatId is not provided', () => {
    expect(() => {
      telegram.unpinChatMessage();
    }).toThrow();
  });

  test('should throw an error when chatId is not a string', () => {
    expect(() => {
      telegram.unpinChatMessage(123456, form);
    }).toThrow();
  });
});
