// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=fd5b57d37f
ROOST_METHOD_SIG_HASH=e0efc7973b


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;

  beforeEach(() => {
    telegram = new Telegram();
    telegram._request = jest.fn();
  });

  describe('editChatInviteLink', () => {
    test('should call _request with correct parameters', () => {
      const chatId = '123';
      const inviteLink = 'http://invite.link';
      const form = {
        expire_date: 1625768356,
        member_limit: 10
      };

      telegram.editChatInviteLink(chatId, inviteLink, form);

      expect(telegram._request).toHaveBeenCalledWith('editChatInviteLink', {
        form: {
          chat_id: chatId,
          invite_link: inviteLink,
          ...form
        }
      });
    });

    test('should set chat_id and invite_link in form when not provided in form', () => {
      const chatId = '123';
      const inviteLink = 'http://invite.link';

      telegram.editChatInviteLink(chatId, inviteLink);

      expect(telegram._request).toHaveBeenCalledWith('editChatInviteLink', {
        form: {
          chat_id: chatId,
          invite_link: inviteLink
        }
      });
    });
  });
});
