// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=98d2e19c48
ROOST_METHOD_SIG_HASH=ed290b22c9


*/

// ********RoostGPT********
const Telegram = require('./telegram');

describe('Telegram', () => {
  let telegram;
  const token = '1234567890:ABCDEFGHIJKLMNOP';
  const baseApiUrl = 'https://api.telegram.org';
  
  beforeEach(() => {
    telegram = new Telegram(token, baseApiUrl);
  });

  test('_buildURL method in production environment', () => {
    const _path = 'sendMessage';
    expect(telegram._buildURL(_path)).toBe(`${baseApiUrl}/bot${token}/${_path}`);
  });

  test('_buildURL method in test environment', () => {
    const _path = 'sendMessage';
    telegram.options.testEnvironment = true;
    expect(telegram._buildURL(_path)).toBe(`${baseApiUrl}/bot${token}/test/${_path}`);
  });

  test('_buildURL method with undefined path', () => {
    const _path = undefined;
    expect(() => {
      telegram._buildURL(_path);
    }).toThrow();
  });
});
