// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=listen_de605ac0dc
ROOST_METHOD_SIG_HASH=listen_7c68ad3120


*/

// ********RoostGPT********
const request = require('supertest');
const app = require('../examples/game/game.js');

describe('Server Listen Test Suite', () => {
  let server;

  beforeAll(done => {
    server = app.listen(4000, done);
  });

  afterAll(done => {
    server.close(done);
  });

  test('should start server at specified port', async () => {
    const response = await request(server).get('/');
    expect(response.status).toBe(200);
  });

  test('should return error for invalid route', async () => {
    const response = await request(server).get('/invalid_route');
    expect(response.status).toBe(404);
  });
});
