// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=onConnect_f245232bc5
ROOST_METHOD_SIG_HASH=onConnect_a7f54306c4


*/

// ********RoostGPT********
const ngrok = require('ngrok');

describe('ngrok.connect', () => {
  let url;
  let consoleOutput = [];
  const originalLog = console.log;

  beforeEach(() => {
    console.log = (...output) => consoleOutput.push(output);
  });

  afterEach(() => {
    console.log = originalLog;
    consoleOutput = [];
  });

  test('successful connection', async () => {
    const port = 8000;
    await ngrok.connect(port, (error, u) => {
      if (error) throw error;
      url = u;
    });
    expect(url).toBeDefined();
    expect(consoleOutput).toContain(`Game tunneled at ${url}`);
  });

  test('connection failure', async () => {
    const port = -1; // Invalid port number
    await expect(ngrok.connect(port, (error, u) => {
      if (error) throw error;
      url = u;
    })).rejects.toThrow();
  });
});
