// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=onEchoText_8a2e43fc98
ROOST_METHOD_SIG_HASH=onEchoText_8fbbfa8592


*/

// ********RoostGPT********
const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot('YOUR_TELEGRAM_BOT_TOKEN', {polling: true});

jest.mock('node-telegram-bot-api');

describe('Telegram Bot', () => {
  let msg;
  let match;

  beforeEach(() => {
    msg = {
      chat: {
        id: 12345
      }
    };

    match = ['/echo Hello', 'Hello'];
  });

  test('responds to /echo command with the same message', () => {
    bot.onText(/\/echo (.+)/, function onEchoText(msg, match) {
      const resp = match[1];
      bot.sendMessage(msg.chat.id, resp);
    });

    expect(bot.sendMessage).toHaveBeenCalledWith(msg.chat.id, match[1]);
  });

  test('does not send message if match array is not correct', () => {
    match = ['/echo ', ''];

    bot.onText(/\/echo (.+)/, function onEchoText(msg, match) {
      const resp = match[1];
      if (!resp) {
        return;
      }
      bot.sendMessage(msg.chat.id, resp);
    });

    expect(bot.sendMessage).not.toHaveBeenCalled();
  });
});
