// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=onMessage_991085522b
ROOST_METHOD_SIG_HASH=onMessage_d3cc9ec5c0


*/

// ********RoostGPT********
const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot('YOUR_TELEGRAM_BOT_TOKEN', {polling: true});

// Test suite
describe('Telegram bot message handler', () => {
  let msg;
  let spy;

  beforeEach(() => {
    msg = { chat: { id: 12345 } };
    spy = jest.spyOn(bot, 'sendMessage');
  });

  afterEach(() => {
    spy.mockRestore();
  });

  test('should send a message that bot is alive on OpenShift', () => {
    bot.emit('message', msg);
    expect(spy).toHaveBeenCalledWith(msg.chat.id, 'I am alive on OpenShift!');
  });

  test('should not send a message if chat id is not provided', () => {
    msg = { chat: {} };
    bot.emit('message', msg);
    expect(spy).not.toHaveBeenCalled();
  });
});
